
import { Subject, Grade } from "../types";

export interface StaticResource {
  title: string;
  description: string;
  grades: Grade[];
}

export const STATIC_RESOURCES: Record<Subject, StaticResource[]> = {
  [Subject.MATH]: [
    // Grade 1
    { title: "חיבור וחיסור עד 20", description: "יסודות החשבון והכרת המספרים בתחום ה-20.", grades: [Grade.GRADE_1] },
    { title: "הכרת צורות גאומטריות בסיסיות", description: "זיהוי ושימוש בריבוע, משולש, עיגול ומלבן.", grades: [Grade.GRADE_1] },
    { title: "שאלות מילוליות פשוטות", description: "פתרון בעיות חשבוניות מתוך סיפורים יומיומיים.", grades: [Grade.GRADE_1] },
    { title: "השוואת מספרים", description: "שימוש בסימנים גדול, קטן ושווה.", grades: [Grade.GRADE_1] },
    // Grade 2
    { title: "חיבור וחיסור במבנה עשרוני עד 100", description: "חישובים מורכבים בטווח ה-100.", grades: [Grade.GRADE_2] },
    { title: "לוח הכפל (2, 5 ו-10)", description: "שליטה בכפולות היסוד הראשונות.", grades: [Grade.GRADE_2] },
    { title: "מדידת אורך וזמן", description: "קריאת שעון ושימוש בסרגל ומטר.", grades: [Grade.GRADE_2] },
    { title: "הכרת המאות הראשונות", description: "מבנה המספר והבנת הערך המקומי.", grades: [Grade.GRADE_2] },
    // Grade 3
    { title: "שליטה בלוח הכפל והחילוק", description: "מיומנות אוטומטית בכל לוח הכפל.", grades: [Grade.GRADE_3] },
    { title: "פתרון תרגילים במאונך", description: "שיטות לחישוב טורים במאונך.", grades: [Grade.GRADE_3] },
    { title: "הכרת השברים הפשוטים", description: "מושגי חצי, רבע ושליש.", grades: [Grade.GRADE_3] },
    { title: "היקף ושטח של מלבן וריבוע", description: "חישובים גאומטריים של שטחים והיקפים.", grades: [Grade.GRADE_3] },
    // Grade 4
    { title: "מספרים עד מיליון", description: "קריאה, כתיבה והשוואה של מספרים גדולים.", grades: [Grade.GRADE_4] },
    { title: "כפל וחילוק במספרים דו-ספרתיים", description: "אלגוריתם הכפל והחילוק הארוך.", grades: [Grade.GRADE_4] },
    { title: "הרחבה וצמצום שברים", description: "פעולות מתקדמות בשברים פשוטים.", grades: [Grade.GRADE_4] },
    { title: "זוויות וסוגי משולשים", description: "מיון משולשים לפי צלעות וזוויות.", grades: [Grade.GRADE_4] },
    // Grade 5
    { title: "פעולות חשבון בשברים פשוטים", description: "חיבור וחיסור שברים בעלי מכנה שונה.", grades: [Grade.GRADE_5] },
    { title: "הכרת המספרים העשרוניים", description: "מעבר בין שברים פשוטים לעשרוניים.", grades: [Grade.GRADE_5] },
    { title: "חישוב נפח תיבה", description: "נוסחאות והבנה תלת-ממדית.", grades: [Grade.GRADE_5] },
    { title: "בעיות מילוליות תנועה ומחיר", description: "פתרון בעיות רב-שלביות מהחיים.", grades: [Grade.GRADE_5] },
    // Grade 6
    { title: "כפל וחילוק מספרים עשרוניים", description: "דיוק בחישוב עם נקודה עשרונית.", grades: [Grade.GRADE_6] },
    { title: "אחוזים והקשר לשברים", description: "הבנת מושג האחוז וחישובו.", grades: [Grade.GRADE_6] },
    { title: "חקירת נתונים וממוצע", description: "קריאת גרפים וחישוב ממוצע חשבוני.", grades: [Grade.GRADE_6] },
    { title: "המעגל והעיגול", description: "הכרת הרדיוס, הקוטר ומושגי יסוד.", grades: [Grade.GRADE_6] },
    // Grade 7
    { title: "מספרים מכוונים", description: "פעולות חשבון עם מספרים חיוביים ושליליים.", grades: [Grade.GRADE_7] },
    { title: "ביטויים אלגבריים וכינוס איברים", description: "מעבר מחשבון לאלגברה.", grades: [Grade.GRADE_7] },
    { title: "פתרון משוואות בנעלם אחד", description: "בידוד הנעלם ופתרון משוואות קוויות.", grades: [Grade.GRADE_7] },
    { title: "זוויות בין ישרים מקבילים", description: "זוויות מתאימות, מתחלפות וקודקודיות.", grades: [Grade.GRADE_7] },
    // Grade 8
    { title: "הפונקציה הקווית", description: "ייצוג אלגברי, גרפי ושיפוע הישר.", grades: [Grade.GRADE_8] },
    { title: "חוקי חזקות", description: "פעולות עם מעריכים ובסיסים.", grades: [Grade.GRADE_8] },
    { title: "מערכת משוואות בשני נעלמים", description: "פתרון בשיטת ההצבה או השוואת מקדמים.", grades: [Grade.GRADE_8] },
    { title: "משפט פיתגורס", description: "חישובי צלעות במשולש ישר זווית.", grades: [Grade.GRADE_8] },
    // Grade 9
    { title: "משוואה ריבועית ופרבולה", description: "פתרון משוואות ממעלה שנייה וחקירה.", grades: [Grade.GRADE_9] },
    { title: "דמיון וחפיפת משולשים", description: "הוכחות ומשפטים בגיאומטריה.", grades: [Grade.GRADE_9] },
    { title: "פירוק לגורמים", description: "טרינום והוצאת גורם משותף.", grades: [Grade.GRADE_9] },
    { title: "הסתברות קלאסית", description: "חישוב סיכויים ומאורעות.", grades: [Grade.GRADE_9] },
    // Grade 10
    { title: "טריגונומטריה בסיסית", description: "סינוס, קוסינוס וטנגנס בישר זווית.", grades: [Grade.GRADE_10] },
    { title: "גאומטריה אנליטית", description: "מרחק בין נקודות ואמצע קטע.", grades: [Grade.GRADE_10] },
    { title: "סדרות חשבוניות", description: "חוקיות ומציאת איברים וסכומים.", grades: [Grade.GRADE_10] },
    { title: "נגזרת של פולינום", description: "תחילת חשבון דיפרנציאלי.", grades: [Grade.GRADE_10] },
    // Grade 11
    { title: "חקירת פונקציות רציונליות ושורש", description: "מציאת אסימפטוטות ונקודות קיצון.", grades: [Grade.GRADE_11] },
    { title: "פונקציות טריגונומטריות", description: "חקירה ומחזוריות של סינוס וקוסינוס.", grades: [Grade.GRADE_11] },
    { title: "בעיות קיצון", description: "מציאת ערך מקסימלי ומינימלי במציאות.", grades: [Grade.GRADE_11] },
    { title: "גאומטריה של המישור", description: "מעגל ומרובעים חסומים.", grades: [Grade.GRADE_11] },
    // Grade 12
    { title: "חשבון אינטגרלי", description: "חישוב שטחים ונפחי סיבוב.", grades: [Grade.GRADE_12] },
    { title: "מספרים מרוכבים", description: "אלגברה וייצוג במישור גאוס.", grades: [Grade.GRADE_12] },
    { title: "פונקציות מעריכיות ולוגריתמיות", description: "חקירה מלאה ושימושים.", grades: [Grade.GRADE_12] },
    { title: "ווקטורים גאומטריים ואלגבריים", description: "חישובים במרחב התלת-ממדי.", grades: [Grade.GRADE_12] }
  ],
  [Subject.HEBREW]: [
    { title: "הקניית קריאה וכתיבה", description: "יסודות הפענוח והכתיבה התקינה.", grades: [Grade.GRADE_1] },
    { title: "סימני פיסוק בסיסיים", description: "שימוש בנקודה וסימן שאלה.", grades: [Grade.GRADE_1] },
    { title: "העשרת אוצר מילים", description: "מילים חדשות ומשמעותן.", grades: [Grade.GRADE_1] },
    { title: "כתיבת משפטים פשוטים", description: "בניית משפט תקין וקצר.", grades: [Grade.GRADE_1] },
    { title: "חוקי כתיב", description: "הבחנה בין אותיות הומופוניות (כמו א' ו-ע').", grades: [Grade.GRADE_2] },
    { title: "זכר ונקבה", description: "התאמה במין בשמות עצם ופעלים.", grades: [Grade.GRADE_2] },
    { title: "יחיד ורבים", description: "הטיית מילים לפי מספר.", grades: [Grade.GRADE_2] },
    { title: "הבנת הנקרא בטקסטים קצרים", description: "מענה על שאלות מתוך טקסט.", grades: [Grade.GRADE_2] },
    { title: "חלקי דיבר", description: "זיהוי שם עצם ופועל.", grades: [Grade.GRADE_3] },
    { title: "שימוש במילון וסדר הא'-ב'", description: "מיומנות חיפוש מילים לפי אלף-בית.", grades: [Grade.GRADE_3] },
    { title: "סיומות שייכות", description: "הוספת קניינים לשמות עצם.", grades: [Grade.GRADE_3] },
    { title: "מבנה המשפט", description: "זיהוי חלקי המשפט הפשוט.", grades: [Grade.GRADE_3] },
    { title: "מילות קישור", description: "חיבור בין חלקי משפט ופסוקיות.", grades: [Grade.GRADE_4] },
    { title: "משפחות מילים ושורשים", description: "זיהוי הקשר הסמנטי בין מילים.", grades: [Grade.GRADE_4] },
    { title: "סימני פיסוק מתקדמים", description: "שימוש בפסיק, נקודתיים ומירכאות.", grades: [Grade.GRADE_4] },
    { title: "הבחנה בין סוגי טקסטים", description: "טקסט מידעי מול סיפורי.", grades: [Grade.GRADE_4] },
    { title: "נטיית הפועל בזמנים", description: "עבר, הווה ועתיד בבניינים.", grades: [Grade.GRADE_5] },
    { title: "שם המספר", description: "כתיבת מספרים נכונה בזכר ונקבה.", grades: [Grade.GRADE_5] },
    { title: "כתיבת סיכום", description: "תמצות טקסט לנקודות מרכזיות.", grades: [Grade.GRADE_5] },
    { title: "מילים בעלות רב-משמעות", description: "הבנת הקשר ופירושי מילים.", grades: [Grade.GRADE_5] },
    { title: "מילים נרדפות וניגודים", description: "עושר לשוני והרחבת אוצר מילים.", grades: [Grade.GRADE_6] },
    { title: "כתיבת טיעון פשוטה", description: "הצגת דעה ונימוק בסיסי.", grades: [Grade.GRADE_6] },
    { title: "ניתוח שירים", description: "הבנת אמצעים אמנותיים בשירה.", grades: [Grade.GRADE_6] },
    { title: "שלבי תהליך הכתיבה", description: "מתכנון ועד עריכה סופית.", grades: [Grade.GRADE_6] },
    { title: "מערכת הצורות", description: "שורש ותבנית בשפה העברית.", grades: [Grade.GRADE_7] },
    { title: "שם הפעולה", description: "מעבר בין פעלים לשמות פעולה.", grades: [Grade.GRADE_7] },
    { title: "הסגרים ודיבור ישיר/עקיף", description: "דרכי מבע ודיווח בטקסט.", grades: [Grade.GRADE_7] },
    { title: "כתיבת מאמר עמדה", description: "ניסוח טענה וביסוסה.", grades: [Grade.GRADE_7] },
    { title: "תחביר בסיסי", description: "נושא ונשוא וניתוח המשפט.", grades: [Grade.GRADE_8] },
    { title: "משלימי שם ופועל", description: "זיהוי תיאורים ותוארי השם.", grades: [Grade.GRADE_8] },
    { title: "גזרת השלמים", description: "נטיית הפועל ללא שינויי שורש.", grades: [Grade.GRADE_8] },
    { title: "השוואה בין טקסטים", description: "מציאת נקודות דמיון ושוני.", grades: [Grade.GRADE_8] },
    { title: "משפטים מורכבים ומחוברים", description: "ניתוח קשרים לוגיים בין פסוקיות.", grades: [Grade.GRADE_9] },
    { title: "הבחנה בין עיקר לטפל", description: "זיהוי הרעיון המרכזי בטקסט.", grades: [Grade.GRADE_9] },
    { title: "דיוקי הגייה", description: "הגייה תקינה של מילים ושמות.", grades: [Grade.GRADE_9] },
    { title: "כתיבה ממזגת", description: "כתיבת טקסט המבוסס על מספר מקורות.", grades: [Grade.GRADE_9] },
    { title: "מערכת הבניינים", description: "משמעויות ונטייה בשבעת הבניינים.", grades: [Grade.GRADE_10] },
    { title: "גזרות חפ\"נ וחפי\"צ", description: "שינויים בשורש בשל עיצורים מיוחדים.", grades: [Grade.GRADE_10] },
    { title: "ניתוח טקסטים אקדמיים", description: "הבנת מבנה מאמר מדעי.", grades: [Grade.GRADE_10] },
    { title: "כתיבת טיעון מורכבת", description: "התמודדות עם טענות נגד.", grades: [Grade.GRADE_10] },
    { title: "גזרות הנחים", description: "נטייה בנחי ע\"ו, ע\"י, ל\"א/ה'.", grades: [Grade.GRADE_11] },
    { title: "סמנטיקה ומטפורות", description: "הבנת משמעות גלויה וסמויה.", grades: [Grade.GRADE_11] },
    { title: "תקינות תחבירית", description: "תיקון שגיאות נפוצות בכתיבה.", grades: [Grade.GRADE_11] },
    { title: "ניתוח טקסטים רב-ערוציים", description: "שילוב מידע ממקורות שונים.", grades: [Grade.GRADE_11] },
    { title: "דרכי תצורה של השם", description: "בסיס וצורן ושיטות נוספות.", grades: [Grade.GRADE_12] },
    { title: "תחביר מתקדם", description: "ניתוח משפטים מורכבים מאוד.", grades: [Grade.GRADE_12] },
    { title: "אמצעים רטוריים בכתיבה", description: "דרכי שכנוע ומבע אמנותי.", grades: [Grade.GRADE_12] },
    { title: "מיזוג מידע ממקורות מגוונים", description: "כתיבה מסכמת ברמה גבוהה.", grades: [Grade.GRADE_12] }
  ],
  [Subject.ENGLISH]: [
    { title: "The ABC and Phonics", description: "Learning letters and their sounds.", grades: [Grade.GRADE_3] },
    { title: "Greetings and Manners", description: "Basic polite phrases.", grades: [Grade.GRADE_3] },
    { title: "Colors and Numbers", description: "Basic vocabulary for counting.", grades: [Grade.GRADE_3] },
    { title: "Basic Animals", description: "Common animal names.", grades: [Grade.GRADE_3] },
    { title: "Reading Simple Words", description: "Blending sounds into words.", grades: [Grade.GRADE_4] },
    { title: "Pronouns", description: "I, you, he, she, it...", grades: [Grade.GRADE_4] },
    { title: "Basic Verbs", description: "Common action words.", grades: [Grade.GRADE_4] },
    { title: "Family Members", description: "Vocabulary for family relations.", grades: [Grade.GRADE_4] },
    { title: "Present Progressive", description: "Actions happening right now.", grades: [Grade.GRADE_5] },
    { title: "Adjectives", description: "Describing people and objects.", grades: [Grade.GRADE_5] },
    { title: "Prepositions of Place", description: "In, on, under, behind...", grades: [Grade.GRADE_5] },
    { title: "Short Paragraphs", description: "Writing simple structured text.", grades: [Grade.GRADE_5] },
    { title: "Past Simple", description: "Talking about finished actions.", grades: [Grade.GRADE_6] },
    { title: "Comparative Adjectives", description: "Comparing two things.", grades: [Grade.GRADE_6] },
    { title: "Telling the Time", description: "Reading analog and digital clocks.", grades: [Grade.GRADE_6] },
    { title: "Modal Verbs", description: "Using can and must.", grades: [Grade.GRADE_6] },
    { title: "Future Simple", description: "Talking about future plans.", grades: [Grade.GRADE_7] },
    { title: "Irregular Verbs", description: "Mastering non-standard past forms.", grades: [Grade.GRADE_7] },
    { title: "Reading Strategies", description: "Techniques for comprehension.", grades: [Grade.GRADE_7] },
    { title: "Unseen Texts", description: "Handling new reading passages.", grades: [Grade.GRADE_7] },
    { title: "Present Perfect", description: "Actions with present relevance.", grades: [Grade.GRADE_8] },
    { title: "Passive Voice", description: "Focusing on the object/action.", grades: [Grade.GRADE_8] },
    { title: "Connectors", description: "Linking words for flow.", grades: [Grade.GRADE_8] },
    { title: "Formal Letter Writing", description: "Structuring business messages.", grades: [Grade.GRADE_8] },
    { title: "First Conditional", description: "Real-world conditions (If... will).", grades: [Grade.GRADE_9] },
    { title: "Relative Clauses", description: "Using who, which, and that.", grades: [Grade.GRADE_9] },
    { title: "Academic Vocabulary", description: "Words for higher level study.", grades: [Grade.GRADE_9] },
    { title: "Presentation Skills", description: "Giving speeches in English.", grades: [Grade.GRADE_9] },
    { title: "Literature Analysis", description: "Poetry and short stories.", grades: [Grade.GRADE_10] },
    { title: "Past Perfect", description: "Actions before another past point.", grades: [Grade.GRADE_10] },
    { title: "Opinion Essays", description: "Writing and defending a viewpoint.", grades: [Grade.GRADE_10] },
    { title: "Using Gerunds", description: "Verbs acting as nouns.", grades: [Grade.GRADE_10] },
    { title: "Reported Speech", description: "Quoting other people indirectly.", grades: [Grade.GRADE_11] },
    { title: "Plays and Novels", description: "In-depth literary study.", grades: [Grade.GRADE_11] },
    { title: "HOTS Strategies", description: "Higher Order Thinking Skills.", grades: [Grade.GRADE_11] },
    { title: "Descriptive Writing", description: "Vivid essays and imagery.", grades: [Grade.GRADE_11] },
    { title: "Global Issues", description: "Analyzing world topics.", grades: [Grade.GRADE_12] },
    { title: "Conditionals 2 & 3", description: "Advanced hypothetical structures.", grades: [Grade.GRADE_12] },
    { title: "Formal Academic Writing", description: "Research-level essay skills.", grades: [Grade.GRADE_12] },
    { title: "Debating Skills", description: "Advanced oral discourse.", grades: [Grade.GRADE_12] }
  ],
  [Subject.SCIENCE]: [
    { title: "עונות השנה", description: "שינויי מזג האוויר והשפעתם.", grades: [Grade.GRADE_1] },
    { title: "חושי האדם", description: "זיהוי ושימוש בחמשת החושים.", grades: [Grade.GRADE_1] },
    { title: "עולם החי והצומח", description: "הכרת הסביבה הקרובה.", grades: [Grade.GRADE_1] },
    { title: "חומרים בסביבה", description: "זיהוי תכונות של חומרים.", grades: [Grade.GRADE_1] },
    { title: "מחזור המים בטבע", description: "שינויי מצבי צבירה.", grades: [Grade.GRADE_2] },
    { title: "תזונה נכונה", description: "חשיבות אבות המזון.", grades: [Grade.GRADE_2] },
    { title: "צמחים והתפתחותם", description: "מהזרע ועד לצמח בוגר.", grades: [Grade.GRADE_2] },
    { title: "כללי בטיחות בחשמל", description: "שימוש בטוח במכשירי חשמל.", grades: [Grade.GRADE_2] },
    { title: "סלעים וקרקעות", description: "סוגי אדמה ושימושיהם.", grades: [Grade.GRADE_3] },
    { title: "גוף האדם ובריאותו", description: "תפקוד איברים מרכזיים.", grades: [Grade.GRADE_3] },
    { title: "תכונות של חומרים", description: "מדידות ותכונות פיזיקליות.", grades: [Grade.GRADE_3] },
    { title: "טכנולוגיה בשירות האדם", description: "המצאות ופתרונות.", grades: [Grade.GRADE_3] },
    { title: "מערכת הנשימה", description: "איך אנחנו נושמים?", grades: [Grade.GRADE_4] },
    { title: "השלד והשרירים", description: "מבנה הגוף והתנועה.", grades: [Grade.GRADE_4] },
    { title: "התאמות בעלי חיים", description: "הישרדות בסביבות שונות.", grades: [Grade.GRADE_4] },
    { title: "שרשרת המזון", description: "יחסי טורף-נטרף בטבע.", grades: [Grade.GRADE_4] },
    { title: "סוגי אנרגיה", description: "אור, חום ותנועה.", grades: [Grade.GRADE_5] },
    { title: "מערכת העיכול", description: "מסלול המזון בגופנו.", grades: [Grade.GRADE_5] },
    { title: "מערכת השמש והיקום", description: "כוכבי הלכת והחלל.", grades: [Grade.GRADE_5] },
    { title: "שימור הסביבה (קיימות)", description: "חשיבות המיחזור.", grades: [Grade.GRADE_5] },
    { title: "חשמל ומגנטיות", description: "מעגלים חשמליים ותכונות.", grades: [Grade.GRADE_6] },
    { title: "מבנה התא", description: "היחידה הבסיסית של החיים.", grades: [Grade.GRADE_6] },
    { title: "אקולוגיה ויחסי גומלין", description: "שיתוף פעולה בטבע.", grades: [Grade.GRADE_6] },
    { title: "תערובות של חומרים", description: "דרכי הפרדה וריכוזים.", grades: [Grade.GRADE_6] },
    { title: "מסה ונפח", description: "מדידות פיזיקליות בסיסיות.", grades: [Grade.GRADE_7] },
    { title: "מבנה האטום", description: "פרוטונים, נייטרונים ואלקטרונים.", grades: [Grade.GRADE_7] },
    { title: "מערכת ההובלה באדם", description: "הלב וכלי הדם.", grades: [Grade.GRADE_7] },
    { title: "מיון יצורים חיים", description: "סיווג ממלכות החי.", grades: [Grade.GRADE_7] },
    { title: "כוחות ותנועה", description: "חוקי התנועה הבסיסיים.", grades: [Grade.GRADE_8] },
    { title: "רבייה בטבע", description: "המשכיות המינים.", grades: [Grade.GRADE_8] },
    { title: "יסודות ותרכובות", description: "הטבלה המחזורית וקשרים.", grades: [Grade.GRADE_8] },
    { title: "אנרגיה חשמלית", description: "ייצור ושימוש בחשמל.", grades: [Grade.GRADE_8] },
    { title: "גנטיקה ותורשה", description: "העברת תכונות לדור הבא.", grades: [Grade.GRADE_9] },
    { title: "מערכת העצבים", description: "המוח ותגובות הגוף.", grades: [Grade.GRADE_9] },
    { title: "קשרים כימיים", description: "קשר יוני, שיתופי ומתכתי.", grades: [Grade.GRADE_9] },
    { title: "חוקי ניוטון", description: "שלושת חוקי התנועה המרכזיים.", grades: [Grade.GRADE_9] },
    { title: "אבולוציה וברירה טבעית", description: "התפתחות המינים.", grades: [Grade.GRADE_10] },
    { title: "קינמטיקה", description: "תיאור תנועה במרחב.", grades: [Grade.GRADE_10] },
    { title: "מבנה וקישור בכימיה", description: "מולקולות וצורות.", grades: [Grade.GRADE_10] },
    { title: "משבר האקלים", description: "היבטים מדעיים של ההתחממות.", grades: [Grade.GRADE_10] },
    { title: "ביוכימיה של התא", description: "תהליכים כימיים ביצורים חיים.", grades: [Grade.GRADE_11] },
    { title: "דינמיקה וכוחות", description: "מכניקה מתקדמת.", grades: [Grade.GRADE_11] },
    { title: "חומצות ובסיסים", description: "תגובות כימיות ו-pH.", grades: [Grade.GRADE_11] },
    { title: "הומיאוסטזיס", description: "שמירה על סביבה יציבה.", grades: [Grade.GRADE_11] },
    { title: "פיזיקה מודרנית", description: "קרינה, חומר ויחסות.", grades: [Grade.GRADE_12] },
    { title: "הנדסה גנטית וביוטכנולוגיה", description: "יישומים ברפואה.", grades: [Grade.GRADE_12] },
    { title: "אנטרופיה ואנרגיה כימית", description: "תרמודינמיקה בסיסית.", grades: [Grade.GRADE_12] },
    { title: "מחקרים אקולוגיים", description: "שיטות עבודה במעבדה.", grades: [Grade.GRADE_12] }
  ],
  [Subject.HISTORY]: [
    // Grade 1
    { title: "סיפור המשפחה שלי", description: "חקר שורשים וסיפורים משפחתיים.", grades: [Grade.GRADE_1] },
    { title: "לוח השנה העברי", description: "הכרת החודשים והחגים כציר זמן.", grades: [Grade.GRADE_1] },
    { title: "חגים כציר זמן", description: "סידור חגי ישראל על פני השנה.", grades: [Grade.GRADE_1] },
    { title: "דמויות מהתנ\"ך כהיסטוריה", description: "הכרת אישים מקראיים בהקשר היסטורי.", grades: [Grade.GRADE_1] },
    // Grade 2
    { title: "המצאות ששינו את העולם", description: "מהגלגל ועד המחשב.", grades: [Grade.GRADE_2] },
    { title: "אליעזר בן יהודה", description: "מחייה השפה העברית.", grades: [Grade.GRADE_2] },
    { title: "שכונות ישנות בעיר שלי", description: "חקר ההיסטוריה המקומית.", grades: [Grade.GRADE_2] },
    { title: "מנהיגי ישראל", description: "הכרת דמויות מנהיגות בולטות.", grades: [Grade.GRADE_2] },
    // Grade 3
    { title: "ראשית הכתב", description: "מהתמונות ועד לאותיות.", grades: [Grade.GRADE_3] },
    { title: "אורח חיים במצרים העתיקה", description: "הפירמידות, הפרעונים והחיים על הנילוס.", grades: [Grade.GRADE_3] },
    { title: "המצאת הגלגל", description: "השפעת הגלגל על התפתחות האנושות.", grades: [Grade.GRADE_3] },
    { title: "סיפורי ראשונים במושבות", description: "התיישבות בארץ ישראל בעת החדשה.", grades: [Grade.GRADE_3] },
    // Grade 4
    { title: "ירושלים בתקופת בית ראשון", description: "עיר דוד והמקדש.", grades: [Grade.GRADE_4] },
    { title: "עולי בבל", description: "שיבת ציון ובניית הבית השני.", grades: [Grade.GRADE_4] },
    { title: "הורדוס ובניין בית שני", description: "מפעלי הבנייה המפוארים.", grades: [Grade.GRADE_4] },
    { title: "המרד הגדול", description: "המאבק ברומא וחורבן הבית.", grades: [Grade.GRADE_4] },
    // Grade 5
    { title: "יוון העתיקה והאולימפיאדה", description: "תרבות, ספורט ופילוסופיה.", grades: [Grade.GRADE_5] },
    { title: "אלכסנדר מוקדון", description: "כיבוש המזרח והמפגש בין תרבויות.", grades: [Grade.GRADE_5] },
    { title: "המפגש בין יהדות להלניזם", description: "השפעות הדדיות וקונפליקטים.", grades: [Grade.GRADE_5] },
    { title: "מרד החשמונאים", description: "סיפור חנוכה והעצמאות היהודית.", grades: [Grade.GRADE_5] },
    // Grade 6
    { title: "רומא והאימפריה", description: "שלטון, חוק ותרבות רומית.", grades: [Grade.GRADE_6] },
    { title: "מרד בר כוכבא", description: "הניסיון האחרון לעצמאות בעת העתיקה.", grades: [Grade.GRADE_6] },
    { title: "חתימת המשנה", description: "רבי יהודה הנשיא ושימור התורה שבעל פה.", grades: [Grade.GRADE_6] },
    { title: "הקהילה היהודית בתפוצות", description: "ראשית הגלות והחיים בקהילה.", grades: [Grade.GRADE_6] },
    // Grade 7
    { title: "עליית האסלאם", description: "מוחמד והתפשטות האימפריה המוסלמית.", grades: [Grade.GRADE_7] },
    { title: "יהדות ספרד ב\"תור הזהב\"", description: "פריחה תרבותית ורוחנית.", grades: [Grade.GRADE_7] },
    { title: "מסעי הצלב והמפגש בין דתות", description: "מאבקים וקשרים בין מזרח למערב.", grades: [Grade.GRADE_7] },
    { title: "הרמב\"ם", description: "דמותו ופועלו של גדול הפילוסופים היהודים.", grades: [Grade.GRADE_7] },
    // Grade 8
    { title: "הרנסנס וההומניזם", description: "התעוררות האמנות והמדע באירופה.", grades: [Grade.GRADE_8] },
    { title: "המהפכה המדעית", description: "קופרניקוס, גלילאו וניוטון.", grades: [Grade.GRADE_8] },
    { title: "המהפכה הצרפתית", description: "נפילת המשטר הישן וזכויות האדם.", grades: [Grade.GRADE_8] },
    { title: "נפוליאון בונפרטה", description: "כיבושיו והשפעתו על אירופה.", grades: [Grade.GRADE_8] },
    // Grade 9
    { title: "המהפכה התעשייתית", description: "קיטור, חשמל ושינויים חברתיים.", grades: [Grade.GRADE_9] },
    { title: "אימפריאליזם", description: "מרוץ המעצמות אחרי מושבות.", grades: [Grade.GRADE_9] },
    { title: "מלחמת העולם הראשונה", description: "הגורמים, המהלכים והסכמי השלום.", grades: [Grade.GRADE_9] },
    { title: "הצהרת בלפור", description: "הכרה בינלאומית בזכות הבית הלאומי.", grades: [Grade.GRADE_9] },
    // Grade 10
    { title: "עליית הנאציזם", description: "המשבר בגרמניה ועליית היטלר לשלטון.", grades: [Grade.GRADE_10] },
    { title: "מלחמת העולם השנייה", description: "החזיתות, המהלכים והניצחון.", grades: [Grade.GRADE_10] },
    { title: "השואה", description: "גורל היהודים תחת השלטון הנאצי.", grades: [Grade.GRADE_10] },
    { title: "המאבק להקמת המדינה", description: "העפלה, התיישבות ומאבק במנדט.", grades: [Grade.GRADE_10] },
    // Grade 11
    { title: "מלחמת העצמאות", description: "שלבי המלחמה והקמת צה\"ל.", grades: [Grade.GRADE_11] },
    { title: "בניית המדינה בעשור הראשון", description: "עלייה המונית, כור ההיתוך וצנע.", grades: [Grade.GRADE_11] },
    { title: "המלחמה הקרה", description: "המאבק הבין-גושי והשפעתו על המזרח התיכון.", grades: [Grade.GRADE_11] },
    { title: "מלחמת ששת הימים", description: "הגורמים, המהלכים והשינוי במפה.", grades: [Grade.GRADE_11] },
    // Grade 12
    { title: "מלחמת יום הכיפורים", description: "ההפתעה, המחדל והניצחון.", grades: [Grade.GRADE_12] },
    { title: "הסכמי שלום", description: "ממצרים ועד הסכמי אברהם.", grades: [Grade.GRADE_12] },
    { title: "החברה הישראלית כפסיפס", description: "שסעים, זהויות ורב-תרבותיות.", grades: [Grade.GRADE_12] },
    { title: "אתגרי המאה ה-21", description: "טכנולוגיה, סביבה וחברה בעולם משתנה.", grades: [Grade.GRADE_12] }
  ],
  [Subject.GEOGRAPHY]: [
    { title: "הכרת המפה והגלובוס", description: "איך קוראים מפות?", grades: [Grade.GRADE_4] },
    { title: "רוחות השמיים", description: "ניווט והתמצאות במרחב.", grades: [Grade.GRADE_4] },
    { title: "סוגי יישובים", description: "עיר, מושב וקיבוץ.", grades: [Grade.GRADE_4] },
    { title: "מפת ארץ ישראל", description: "זיהוי אזורים מרכזיים.", grades: [Grade.GRADE_4] },
    { title: "אזורי הארץ", description: "הנגב, הגליל ומישור החוף.", grades: [Grade.GRADE_5] },
    { title: "משאבי טבע", description: "מים, שמש ומחצבים בישראל.", grades: [Grade.GRADE_5] },
    { title: "אקלים ומזג אוויר", description: "סוגי אקלים במרחב.", grades: [Grade.GRADE_5] },
    { title: "הגירה", description: "תנועת אוכלוסייה בעולם.", grades: [Grade.GRADE_5] },
    { title: "יבשות ואוקיינוסים", description: "פריסת היבשות בעולם.", grades: [Grade.GRADE_6] },
    { title: "תופעת הגלובליזציה", description: "הכפר הגלובלי והשפעותיו.", grades: [Grade.GRADE_6] },
    { title: "צפיפות אוכלוסין", description: "איפה אנשים בוחרים לגור?", grades: [Grade.GRADE_6] },
    { title: "תיירות עולמית", description: "השפעת התיירות על המרחב.", grades: [Grade.GRADE_6] },
    { title: "טקטוניקה", description: "מבנה כדור הארץ והלוחות.", grades: [Grade.GRADE_7] },
    { title: "הרי געש ורעידות אדמה", description: "גורמים והיערכות לאסונות.", grades: [Grade.GRADE_7] },
    { title: "בעיית המים בעולם", description: "מחסור במים מתוקים.", grades: [Grade.GRADE_7] },
    { title: "עיור", description: "צמיחת הערים הגדולות.", grades: [Grade.GRADE_7] },
    { title: "המזרח התיכון", description: "היבטים גאוגרפיים ופוליטיים.", grades: [Grade.GRADE_8] },
    { title: "משאבי אנרגיה", description: "נפט, גז ואנרגיה ירוקה.", grades: [Grade.GRADE_8] },
    { title: "קונפליקטים גאופוליטיים", description: "מאבקים על טריטוריה.", grades: [Grade.GRADE_8] },
    { title: "איכות הסביבה", description: "זיהום אוויר ומים בעולם.", grades: [Grade.GRADE_8] },
    { title: "מדינות מפותחות מול מתפתחות", description: "מאפייני העולם המודרני.", grades: [Grade.GRADE_9] },
    { title: "התחממות גלובלית", description: "שינויי אקלים והשלכותיהם.", grades: [Grade.GRADE_9] },
    { title: "אסונות טבע", description: "שיטפונות, הוריקנים ובצורת.", grades: [Grade.GRADE_9] },
    { title: "שימוש במערכות GIS", description: "מערכות מידע גאוגרפיות.", grades: [Grade.GRADE_9] },
    { title: "ניתוח תצלומי אוויר", description: "פענוח תצ\"אות.", grades: [Grade.GRADE_10] },
    { title: "גאוגרפיה עירונית", description: "מבנה העיר המודרנית.", grades: [Grade.GRADE_10] },
    { title: "כלכלה עולמית", description: "סחר בינלאומי וארגונים.", grades: [Grade.GRADE_10] },
    { title: "תכנון מרחבי", description: "איך מתכננים עיר וסביבה?", grades: [Grade.GRADE_10] },
    { title: "חקר האקלים בישראל", description: "תופעות אקלימיות מקומיות.", grades: [Grade.GRADE_11] },
    { title: "סוגיות חברה וכלכלה בארץ", description: "הפסיפס האנושי של ישראל.", grades: [Grade.GRADE_11] },
    { title: "אגן הים התיכון", description: "קשרים גאוגרפיים אזוריים.", grades: [Grade.GRADE_11] },
    { title: "משאבי מים מקומיים", description: "התפלה וניהול המים.", grades: [Grade.GRADE_11] },
    { title: "פיתוח בר-קיימא", description: "איזון בין פיתוח לשימור.", grades: [Grade.GRADE_12] },
    { title: "גאופוליטיקה עכשווית", description: "יחסים בינלאומיים במרחב.", grades: [Grade.GRADE_12] },
    { title: "שינויים דמוגרפיים בעולם", description: "הזדקנות וילודה.", grades: [Grade.GRADE_12] },
    { title: "ניהול סיכונים סביבתיים", description: "התמודדות עם משברים.", grades: [Grade.GRADE_12] }
  ],
  [Subject.BIBLE]: [
    { title: "סיפורי הבריאה", description: "ראשית העולם בראי המקרא.", grades: [Grade.GRADE_2] },
    { title: "האבות והאימהות", description: "סיפורי אברהם, יצחק ויעקב.", grades: [Grade.GRADE_2] },
    { title: "המבול ותיבת נח", description: "סיפור הצלת העולם.", grades: [Grade.GRADE_2] },
    { title: "מגדל בבל", description: "ראשית השפות והעמים.", grades: [Grade.GRADE_2] },
    { title: "יציאת מצרים", description: "מעבדות לחירות ועשר המכות.", grades: [Grade.GRADE_3] },
    { title: "עשרת הדיברות", description: "הבסיס המוסרי של העם.", grades: [Grade.GRADE_3] },
    { title: "נדודי בני ישראל במדבר", description: "המסע לארץ כנען.", grades: [Grade.GRADE_3] },
    { title: "דמותו של משה", description: "חייו ומנהיגותו של משה.", grades: [Grade.GRADE_3] },
    { title: "ספר יהושע", description: "כיבוש הארץ וחלוקת הנחלות.", grades: [Grade.GRADE_4] },
    { title: "ספר שופטים", description: "תקופת המנהיגות המקומית.", grades: [Grade.GRADE_4] },
    { title: "דבורה ושמשון", description: "דמויות מופת בשופטים.", grades: [Grade.GRADE_4] },
    { title: "מנהיגות בתקופת המקרא", description: "תכונות המנהיג בעבר.", grades: [Grade.GRADE_4] },
    { title: "ספר שמואל", description: "ראשית המלוכה בישראל.", grades: [Grade.GRADE_5] },
    { title: "המלך שאול", description: "עלייתו ונפילתו של המלך הראשון.", grades: [Grade.GRADE_5] },
    { title: "דוד וגוליית", description: "סיפור הגבורה והאמונה.", grades: [Grade.GRADE_5] },
    { title: "מלכות דוד בירושלים", description: "קביעת עיר הבירה.", grades: [Grade.GRADE_5] },
    { title: "ספר מלכים", description: "תקופת הזוהר והפילוג.", grades: [Grade.GRADE_6] },
    { title: "שלמה המלך ובניין המקדש", description: "חכמתו ומפעלו.", grades: [Grade.GRADE_6] },
    { title: "פילוג המלוכה", description: "הפיצול לישראל ויהודה.", grades: [Grade.GRADE_6] },
    { title: "אליהו הנביא", description: "מאבק בנביאי הבעל.", grades: [Grade.GRADE_6] },
    { title: "גלות בבל", description: "חורבן הבית הראשון.", grades: [Grade.GRADE_7] },
    { title: "שיבת ציון", description: "עזרא ונחמיה והחזרה לארץ.", grades: [Grade.GRADE_7] },
    { title: "מגילת אסתר", description: "סיפור הגאולה בפרס.", grades: [Grade.GRADE_7] },
    { title: "חורבן הבית הראשון", description: "גורמים וקינות.", grades: [Grade.GRADE_7] },
    { title: "נביאי בית ראשון", description: "עמוס והושע - נבואות זעם.", grades: [Grade.GRADE_8] },
    { title: "נבואות נחמה", description: "חזון הגאולה של הנביאים.", grades: [Grade.GRADE_8] },
    { title: "ספר יונה", description: "הבריחה מהשליחות והתשובה.", grades: [Grade.GRADE_8] },
    { title: "מושגי צדק חברתי", description: "המסר המוסרי של הנביאים.", grades: [Grade.GRADE_8] },
    { title: "ספרות החכמה", description: "משלי וקהלת - פניני חכמה.", grades: [Grade.GRADE_9] },
    { title: "ספר איוב", description: "התמודדות עם סבל הצדיק.", grades: [Grade.GRADE_9] },
    { title: "תהילים", description: "מזמורי תפילה ושבח.", grades: [Grade.GRADE_9] },
    { title: "שאלת הגמול", description: "צדיק ורע לו במקרא.", grades: [Grade.GRADE_9] },
    { title: "חוקי התורה", description: "חוקים חברתיים ופולחניים.", grades: [Grade.GRADE_10] },
    { title: "סיפורי ראשית", description: "ניתוח ספרותי מעמיק.", grades: [Grade.GRADE_10] },
    { title: "המאבק בעבודה זרה", description: "אמונות במזרח הקדום.", grades: [Grade.GRADE_10] },
    { title: "פרשנות חז\"ל", description: "איך פירשו חכמים את הטקסט?", grades: [Grade.GRADE_10] },
    { title: "נביאי אמת ושקר", description: "זיהוי הנביא והמסר.", grades: [Grade.GRADE_11] },
    { title: "ירמיהו וחורבן ירושלים", description: "נבואות הלב השבור.", grades: [Grade.GRADE_11] },
    { title: "חטאי דוד", description: "דמות המנהיג האנושי.", grades: [Grade.GRADE_11] },
    { title: "מנהיגות בעת משבר", description: "ניהול קהילה ועם.", grades: [Grade.GRADE_11] },
    { title: "חמש מגילות", description: "שיר השירים ורות.", grades: [Grade.GRADE_12] },
    { title: "חזון אחרית הימים", description: "העתיד בראי הנבואה.", grades: [Grade.GRADE_12] },
    { title: "מיתוסים במזרח הקדום", description: "המקרא מול תרבויות שכנות.", grades: [Grade.GRADE_12] },
    { title: "פרשנות מודרנית", description: "ביקורת המקרא וגישות חדשות.", grades: [Grade.GRADE_12] }
  ],
  [Subject.CIVICS]: [
    { title: "זכויות האדם והאזרח", description: "הכרת הזכויות הטבעיות.", grades: [Grade.GRADE_9] },
    { title: "שלטון החוק", description: "חשיבות החוק בדמוקרטיה.", grades: [Grade.GRADE_9] },
    { title: "עקרון הפרדת הרשויות", description: "איזונים ובלמים בשלטון.", grades: [Grade.GRADE_9] },
    { title: "סמלי המדינה", description: "היבטים חוקיים וערכיים.", grades: [Grade.GRADE_9] },
    { title: "הכרזת העצמאות", description: "ניתוח המסמך המכונן.", grades: [Grade.GRADE_10] },
    { title: "יהודית ודמוקרטית", description: "הגדרת זהות המדינה.", grades: [Grade.GRADE_10] },
    { title: "הרשות המחוקקת", description: "תפקיד הכנסת.", grades: [Grade.GRADE_10] },
    { title: "מפלגות ובחירות", description: "איך עובדת הדמוקרטיה?", grades: [Grade.GRADE_10] },
    { title: "הרשות המבצעת", description: "תפקיד הממשלה והשרים.", grades: [Grade.GRADE_11] },
    { title: "הרשות השופטת", description: "עצמאות בית המשפט.", grades: [Grade.GRADE_11] },
    { title: "תקשורת ודמוקרטיה", description: "חופש הביטוי והעיתונות.", grades: [Grade.GRADE_11] },
    { title: "קבוצות בחברה הישראלית", description: "השסעים והחיים המשותפים.", grades: [Grade.GRADE_11] },
    { title: "מנגנוני פיקוח וביקורת", description: "מבקר המדינה והנציב.", grades: [Grade.GRADE_12] },
    { title: "סוגיות דת ומדינה", description: "הסטטוס קוו והשסע הדתי.", grades: [Grade.GRADE_12] },
    { title: "המערכת המקומית", description: "תפקיד הרשויות המקומיות.", grades: [Grade.GRADE_12] },
    { title: "משפט חוקתי בישראל", description: "חוקי היסוד של המדינה.", grades: [Grade.GRADE_12] }
  ],
  [Subject.OTHER]: []
};
